### ISSUE TITLE
rspec tests inconclusive for #void_last_transaction

### ISSUE THREAD

**Issue by fbohz** [learn-co-curriculum/oo-cash-register#27]
Hello there the test on rpec for this method really do not really test this method you could literally pass it by writing this:

 ```  
def void_last_transaction
    self.total = 0 
    self.total.to_f
 end
```

So it should really pass test by adding two items. Maybe something like this? (learning how to do tests)

```
describe '#void_last_transaction' do
  it 'subtracts the last transaction from the total' do
    new_register = CashRegister.new
    cash_register.add_item("tomato", 1.76)
    cash_register.add_item("eggs", 2.00)
    expect{cash_register.void_last_transaction}.to change{cash_register.total}.from(3.76).to(1.76)
  end
end
```

**Comment by maxwellbenton** [comment]
Hi @fbohz,

Thank you for spotting this and providing feedback. We've updated the tests for `void_last_transaction` so that they run multiple checks. This will prevent solutions like the one you provided as more than one item is added, and the total does not go down toe 0.0, which should resolve this issue.

Thank you for contributing to a Learn lesson!
